### ISSUE TITLE
example for use SyncReadNumber and AsyncReadNumber

### ISSUE THREAD

**Issue by drandule** [M-o-a-T/asyncari#9]
Hello
can you give me some examples for  use SyncReadNumber and AsyncReadNumber

thanks advance

**Comment by fastalan** [comment]
Hey, can you tell me what package versions you built it with and what version of python? My docker build is failing and I'm looping around on Dependencies.

# Use the official Python image from the Docker Hub
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy requirements file if you have one, otherwise, directly install needed packages
# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade pip
# Alternatively, install the required packages directly
RUN pip install --no-cache-dir h11 \
#    && pip install --root-user-action ignore --no-cache-dir asks==2.4.12 \
    && pip install --no-cache-dir asks\
    && pip install --no-cache-dir attrs \
    && pip install --no-cache-dir asyncwebsockets \
    && pip install --no-cache-dir anyio \
    && pip install --no-cache-dir asyncari

**Comment by smurfix** [comment]
Please don't add to unrelated issues! (Also why the heck do you freeze anyio to 3.x?)

**Comment by smurfix** [comment]
There's a SyncReadNumber example in `examples/zoom`.

Please don't use issues for questions; that's what discussions are for.
